#! /bin/bash

# Modified Dasgeeks AutinstallBashScrips/installscript 
# https://github.com/dasgeekchannel/AutoInstallBashScripts/blob/master/installscript

install='sudo apt-get install -y'
update='sudo apt-get update;sudo apt-get upgrade -y'

#list of applications to install
# Git
# Chrome
# Steam
# Discord (SNAP)
# VLC
# Simplescreenrecorder
# TimeShift
# Gufw
# neofetch
# Nvidia Drivers
# Openssh server
# psensor
#
#
#
#
#
#
#
#
#
#
#
#
#
#
