version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /MEDIA/Nextcloud/config:/config
      - /MEDIA/Nextcloud/data:/data
    ports:
      - 443:443
    restart: unless-stopped