#
# Work in Progress
# Taken from https://github.com/turtl/server
# Be aware: after you cancel the docker-compose the data will be lost. For productive usage you may want to store the postgres-data inside a docker volume.
#
version: '2.1'

services:
  turtl-server:
    container_name: 'turtl'
    build:
      context: ./
    environment:
      TURTL_DB_HOST: postgres-db
      TURTL_DB_PORT: 5432
      TURTL_DB_DATABASE: turtl
      TURTL_DB_USER: turtl
      TURTL_DB_PASSWORD: turtl
      TURTL_APP_SECURE_HASH_SALT: abuHassN892MMn
    ports:
      - 8181:8181
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: turtl
      POSTGRES_USER: turtl
      POSTGRES_DB: turtl
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U turtl"]
      interval: 10s
      timeout: 5s
      retries: 5